### ISSUE TITLE
Development build fails on multi-module parent project

### ISSUE THREAD

**Issue by conteit** [egineering-llc/gitflow-helper-maven-plugin#51]
I've updated to version 1.5.2 in order to solve an issue on release process, but now I get the following stack trace when trying to build from origin/develop.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project tl4-parent: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project tl4-parent: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter
	at org.apache.maven.plugin.deploy.DeployMojo.getDeploymentRepository(DeployMojo.java:343)
	at org.apache.maven.plugin.deploy.DeployMojo.deployProject(DeployMojo.java:206)
	at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:169)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
```

Plugins configuration is:
```xml
<plugin>
				<groupId>com.e-gineering</groupId>
				<artifactId>gitflow-helper-maven-plugin</artifactId>
				<version>1.5.2</version>
				<configuration>
					<releaseDeploymentRepository>${release.repository}</releaseDeploymentRepository>
					<stageDeploymentRepository>${stage.repository}</stageDeploymentRepository>
					<snapshotDeploymentRepository>${snapshot.repository}</snapshotDeploymentRepository>
					<tag>${project.version}</tag>
				</configuration>
				<extensions>true</extensions>
				<executions>
					<execution>
						<goals>
							<goal>enforce-versions</goal>
							<goal>retarget-deploy</goal>
							<goal>tag-master</goal>
							<goal>promote-master</goal>
						</goals>
						<configuration>
							<developmentBranchPattern>origin/develop</developmentBranchPattern>
						</configuration>
					</execution>
				</executions>
			</plugin>
```
with repository variables set as: `<id>::<layout>::<url>::<uniqueVersion>`.

**Comment by conteit** [comment]
Problem solved: I had a typo in the project version (SNPSHOT instead of SNAPSHOT).

I've understood it when I tried with an older plugin version (1.2.2) which provided a clearer error description.
