### ISSUE TITLE
enforce-versions without project.version in branch name

### ISSUE THREAD

**Issue by pentavalle** [egineering-llc/gitflow-helper-maven-plugin#78]
Hi,
in my company process workflow we use release branch to put sw that must be validated by QA team, when we start the branch, let's say its name is release/1.2.3 and pom.xml has this version. Sw goes to QA but if a bug it's discovered we have to fix it and increment sw version for example to 1.2.3.1 and then release again to QA from same branch.
Using enforce-versions goal this is not possible because project.version in pom.xml is different from project version in branch name (1.2.3 vs 1.2.3.1).
I tried using releaseBranchPattern=(origin/)?release/.* to skip version check but it gives a NPE.
I think there will be same problem with hotfix branch.
I like other enforcements that this goal accomplish, especially for SNAPSHOT suffix, but version number enforcement it's too much for us.
Can you provide a way to disable this check, or do you think there's an alternative way for us to handle versions in branch?

Thanks Andrea

**Comment by bvarner** [comment]
If you could provide a stack trace of the NPE, that'd be helpful.

It sounds like what you're wanting is 'support branch' versioning semantics on the release branch and hotfix branches. Does that sound about 'right'?

I'm confused as to why you would increment a 'yet to really be released' artifact's version number. The point of a release branch is to work _toward_ a release, and once it's 'good', merge it. I also realize that this plugin has a highly opinionated versioning structure, and in this case I'm inclined to tell you just to disable the `enforce-versions` if you're not going to stick to a gitflow versioning scheme.

All that said, you may be able to cook up a more complex regex and have it 'work' for you.


The pattern, `(origin/)?release/([0-9]*\.[0-9]*\.[0-9])` would match the following branch names, and expect the pom.xml version to be `1.3.2`:

```
release/1.3.2
release/1.3.2.1
release/1.3.2.1-qa1
release/1.3.2-qa1
origin/release/1.3.2
origin/release/1.3.2.1
origin/release/1.3.2.1-qa1
origin/release/1.3.2-qa1
```

**Comment by bvarner** [comment]
And thank you, Andrea for the feedback!

**Comment by pentavalle** [comment]
My company wants QA version numbers to be unique, so we can identify what was deployed without knowing the deployment time. If we keep same version between multiple QA releases from release branch, we can have same version with different content, like for snapshots.
I agree that using versioning scheme like release/1.3.2 branch and pom version numbers like 1.3.2-QA1, 1.3.2-QA2 and so on until final release that will become 1.3.2 beforge merging into master branch would be a good solution, together with a regex like the one you suggest.

Anyway, this is NPE log:
`[ERROR] Failed to execute goal com.e-gineering:gitflow-helper-maven-plugin:1.7.2:enforce-versions (default) on project test-ci-parent: Execution default of goal com.e-gineering:gitflow-helper-maven-plugin:1.7.2:enforce-versions failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.e-gineering:gitflow-helper-maven-plugin:1.7.2:enforce-versions (default) on project test-ci-parent: Execution default of goal com.e-gineering:gitflow-helper-maven-plugin:1.7.2:enforce-versions failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.e-gineering:gitflow-helper-maven-plugin:1.7.2:enforce-versions failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at com.e_gineering.maven.gitflowhelper.EnforceVersionsMojo.execute(EnforceVersionsMojo.java:34)
        at com.e_gineering.maven.gitflowhelper.AbstractGitflowBranchMojo.logExecute(AbstractGitflowBranchMojo.java:66)
        at com.e_gineering.maven.gitflowhelper.AbstractGitflowBranchMojo.execute(AbstractGitflowBranchMojo.java:100)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more`

**Comment by pentavalle** [comment]
Mmmh, no, my mistake, you suggested to make different branch names but keeping same pom version number, I tried but I'd want to use same branch with different pom version numbers, and I think it's not possible with regex.
Try looking at this picture [https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/#hotfix-branches](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/#hotfix-branches) and tell me what you think.

**Comment by bvarner** [comment]
*story time*
Shortly after releasing this plugin, I received a really nice (and encouraging) letter from a former coworker and friend, who thought this was all a great idea. His only beef, was with the versioning enforcement, and it's highly opinionated view on versions. He wanted true semver support.
*/story time*

I get it. I really, honestly do.

From an artifact management standpoint it would seem easier to track artifact / release lineage in a repository. With communicating changes amongst testing teams (which probably don't have access to the SCM) it makes sense to include build metadata attached to the delivered artifacts.

The difficulty here is:
* Maven project versions aren't about builds. They're about releases.
** If you commit to bump the pom.xml version, you change the 'source' and the resulting artifacts.
** Maven expects you to _manage_ your project version as part of the POM, rather than derive it from the branch name and some other arbitrary counter or metadata source from outside the project, and makes no allowance for dropping a qualifier from a semver build as if it were the 'final' build. Because Maven project versions are about releases, not builds.

The original source of gitflow makes no mention of this conundrum. (indeed, it's kind of a maven problem)
http://nvie.com/posts/a-successful-git-branching-model/

I've read the GitVersion link you sent, and have some observations.
Their piece on [https://gitversion.readthedocs.io/en/latest/more-info/version-increments/](Version Increments) mentions:

```
Semantic Versioning is all about releases, not builds. This means that the version only increases after you release, this directly conflicts with the concept of published CI builds.
```

So from this, I've always had the mindset that the pom.xml `$(project.version}` should reflect the _release_. The release artifacts should placed in an appropriate repository, and the artifacts for the release should be *promoted* when the source which was built is merged. 

I'm not opposed to semver management, but I don't believe semver has any place in `${project.version}`, since that's not what `${project.version}` was meant to convey.

If you need a way to track semver builds or other metadata appended to a build you should perhaps consider a manner of reporting that data in the app, without imposing it to the artifact release. (Examples I've seen are build-generated strings in 'about' pages, REST endpoints to get the deployed semver, etc.)

So, this is why I recommend you just disable `enforce-versions`, if you're going to try to semver manage your `${project.version}`.

**Comment by bvarner** [comment]
Another thing you could do, would be to track semver data in a separate file (or have it generated by the build) and use the maven-build-helper-plugin to attach that file to the set of artifacts deployed to your nexus repository. That would at least track the build metadata as part of the release artifact.

Also, the link you sent mentioned that the 'grey boxes' are _tags_, it never mentions updating SCMed release versions as part of your project source.

**Comment by pentavalle** [comment]
Your support was great! I think I have enough to discuss these things with other people here in my company and make some decisions on how to go on.
Thank you, and I want to say that your plugin is great!
